stages:
  - deploy

deploy-job:
  stage: deploy
  image: node:20.15.0
  before_script:
    - "command -v ssh-agent >/dev/null || ( apk add --update openssh )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $SSH_PORT $SSH_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "Installing dependencies..."
    - apt-get update -qq && apt-get install -y -qq sshpass
    - apt-get install -y -qq rsync
    - echo "Setup..."
    - git clone https://gitlab.com/kiwilan/markdown-tools.git
    - cd markdown-tools
    - npm install -g pnpm
    - pnpm i
    - echo "Building..."
    - pnpm build
    - echo "Deploying..."
  script:
    - rsync -azPhhr -e "ssh -p $SSH_PORT" dist $SSH_USER@$SSH_IP:/var/www/$CI_PROJECT_NAME/dist-$CI_JOB_ID
    - ssh -p $SSH_PORT $SSH_USER@$SSH_IP "
      . ~/.zshrc &&
      cd /var/www/$CI_PROJECT_NAME &&
      git pull &&
      docker cp dist-$CI_JOB_ID $DOCKER_CONTAINER:/app/ &&
      docker exec $DOCKER_CONTAINER rm -rf dist &&
      rm -rf dist &&
      cp -r dist-$CI_JOB_ID/dist dist &&
      rm -rf dist-$CI_JOB_ID &&
      docker cp dist $DOCKER_CONTAINER:/app/ &&
      docker restart $DOCKER_CONTAINER &&
      rm -rf dist &&
      notifier discord '$CI_PROJECT_TITLE deployed'"
  only:
    - main
