/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/App/Button.vue')['default']
    FieldText: typeof import('./src/components/Field/Text.vue')['default']
    LayoutFooter: typeof import('./src/components/Layout/Footer.vue')['default']
    LayoutNavbar: typeof import('./src/components/Layout/Navbar.vue')['default']
  }
}
