// This file is auto generated by TypescriptableLaravel.
declare namespace App.Models {
  export type User = {
    id: number
    name: string
    email: string
    email_verified_at: Date
    two_factor_confirmed_at?: Date
    current_team_id?: number
    profile_photo_path?: string
    created_at?: Date
    updated_at?: Date
    profile_photo_url?: any
  }
}

declare namespace App {
  export type PaginateLink = {
    url: string;
    label: string;
    active: boolean;
  };
  export type Paginate<T = any> = {
    data: T[];
    current_page: number;
    first_page_url: string;
    from: number;
    last_page: number;
    last_page_url: string;
    links: App.PaginateLink[];
    next_page_url: string;
    path: string;
    per_page: number;
    prev_page_url: string;
    to: number;
    total: number;
  };
  export type ApiPaginate<T = any> = {
    data: T[];
    links: {
      first?: string;
      last?: string;
      prev?: string;
      next?: string;
    };
    meta: {
      current_page: number;
      from: number;
      last_page: number;
      links: App.PaginateLink[];
      path: string;
      per_page: number;
      to: number;
      total: number;
    };
  };
}